name: easy_auto_form
description: EasyAutoForm is a Flutter package that generates a Form based on a given entity, supporting a variety of entity types and input types.
version: 0.0.2+6
homepage: https://github.com/CesareIsHere/easy_auto_form

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

example:
  path: example/example.dart

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
